# Permalinks
permalink:           pretty

# Setup
title:               sligocki
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Shawn Ligocki
  email:             sligocki@gmail.com

# Gems
plugins:
  - jekyll-paginate

